apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailthing-data
  namespace: mailthing
  labels:
    app.kubernetes.io/name: mailthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
